version: '3'

services:
  db:
    image: postgres:14
    restart: always
    container_name: auth-postgres
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "2345:5432"

#  sonarqube:
#    container_name: "sonarqube"
#    image: "sonarqube:9.9.1-community"
#    volumes:
#      - ./sonarqube/extensions:/opt/sonarqube/extensions
#      - ./sonarqube/logs:/opt/sonarqube/logs
#      - ./sonarqube/data:/opt/sonarqube/data
#    expose:
#      - "9000"
#    ports:
#      - "9000:9000"
